### ISSUE TITLE
Use snake_case, not camelCase

### ISSUE THREAD

**Issue by Eric-Arellano** [Anakin33/pythonProjects#1]
In Python, you use snake_case for everything (lowercase with `_` between words). The only time in Python you use camelCase is when creating a new class, which we'll get to later, and with constants which use UPPER_CASE.

This is different to JavaScript, where most things are camelCase.

To close out this issue, you'll need to rename every file, function, and variable. When doing this, try out PyCharm's "Renaming" functionality! https://www.jetbrains.com/help/pycharm/rename-refactorings.html

**Comment by Anakin33** [comment]
Fixed!

**Comment by Eric-Arellano** [comment]
You also want to rename the folders and the file names. You can again use PyCharm to do this. Google "Pycharm rename file" if you can't figure out through their UI how to do it.
