### ISSUE TITLE
Move docstring to the top of the file

### ISSUE THREAD

**Issue by Eric-Arellano** [Anakin33/pythonProjects#2]
I'm glad you discovered docstring! As a recap, it's the standard way to add documentation to your functions and your files. It looks like this:

```python
def my_super_cool_function():
  """This function hacks into people's debt.
  
  Note it only works if the user has an AmEx domiciled in Idaho and uses a Windows Phone."""
  pass
```

The one improvement you can make is moving the docstrings to the very top of their files, because it's describing the file. Right now you have it at the bottom of the files, meaning it won't be recognized as a valid docstring.

**Comment by Anakin33** [comment]
I think i fixed what you were saying!
