### ISSUE TITLE
Use f-strings (string interpolation)

### ISSUE THREAD

**Issue by Eric-Arellano** [Anakin33/pythonProjects#3]
Right now you're printing your functions with multiple arguments, each its own string and separated by a comma.

```python
print('Your roll is ', num, '. Would you like to roll again?')
```

This works, but there's a far better way to do this in Python. f-strings! It's a special type of string. You put `f` in front of the quotes, and then can refer to other variables and arbitrary Python code within it by surrounding the reference with `{}`.

```python
print(f'Your roll is {num}. Would you like to roll again?')

f'(You can even execute Python code within it like this! 1 + 1 = {1+1}'
```

Input that second string into iPython and see what you get! Then try creating a variable of a list, e.g. `my_list = [1, 2, 3]`, and refer to that variable in an f-string.

**Comment by Anakin33** [comment]
Much cleaner!! fixed
