### ISSUE TITLE
Return without intermediate variable

### ISSUE THREAD

**Issue by Eric-Arellano** [Anakin33/pythonProjects#4]
This function can be improved further:
```python
def rollDice():
    ranNum = random.randint(1, 6)
    return ranNum
```

You see how you only create the variable `ranNum` in order to return it immediately after? You don't need it for any intermediate computations.

In general, it's better style to simply return right away that last expression without creating the variable. It has less lines of code and avoids you having to name the variable, which is the hardest thing in programming! (Warning that less lines of code is not always better, but in general it's desirable).

Change to
```python
def rollDice():
    return random.randint(1, 6)
```

You had 2-3 instances of this pattern.

**Comment by Anakin33** [comment]
okay! I originally had this but wasn't sure if it worked in python!!

**Comment by Eric-Arellano** [comment]
Hm okay. Can you explain to me why this _does_ work? What does the intermediate variable do? We can talk this over on the phone. This is an important fundamental concept to internalize.
