### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by Eric-Arellano** [Anakin33/pythonProjects#5]
First off good job setting up the github project! 

If you look at the folders, there's one improvement to make. You have the folders `venv` and `.idea` in the repository, which you don't want. `venv` is what's called a "virtual environment", and is used to setup your Python project and its dependencies. ".idea" is the folder PyCharm uses and auto-generates.

So how do you get rid of these? The .gitignore file. Check out this tutorial on .gitignore, and implement one for this project https://www.atlassian.com/git/tutorials/saving-changes/gitignore.

Also see if you can figure out how to remove the `venv` and `.idea` folders. You don't want to physically delete them on your computer! Instead, you want git to ignore them and to stop including them in the git repository. A key phrase you may want to search is "git remove folder already merged into master"

**Comment by Anakin33** [comment]
FIXED!!!!
