### ISSUE TITLE
New content: Python main() functions

### ISSUE THREAD

**Issue by Eric-Arellano** [Anakin33/pythonProjects#6]
Right now, you have in your files lines like this defined at the module level
```python
def should_roll():
  ...

...

should_roll()
```

See how the call `should_roll()` has no indentation? That means it's at the module level, and it will execute whenever you either call the file or even import it!

Little experiment to see how this import works. In the folder `roll_dice_project`, create a new file `test.py`. Have this in it 

```python
print("Before import")
import roll_dice  # you may need to do `import roll_dice_project.roll_dice
print("After import")
```

Did you have something print in between those two print statements? If so, that's probably not what we intended for. Simply importing a file shouldn't make it execute!

This is why Python has something called the main function. Check out this tutorial explaining it and then implement for each project. https://www.journaldev.com/17752/python-main-function This concept can be a little confusing, and the important thing to focus on is the intuition for why we should use a main function.

**Comment by Anakin33** [comment]
I understand the logic! I am not able to import from the module though.

**Comment by Anakin33** [comment]
Done!
